/**
 * add person
 */
INSERT INTO PERSON(USERNAME, AGE, JOB_CODE)VALUES('test', 30, 1);
/**
 * add job
 */
INSERT INTO JOB(JOB_CODE, DESCRIPTION)VALUES(1, 'engineer');
INSERT INTO JOB(JOB_CODE, DESCRIPTION)VALUES(2, 'doctor');
