-- DROP TABLE IF EXISTS PERSON;
-- DROP TABLE IF EXISTS PRODUCT;

/**
 * 使用者資訊
 */
CREATE TABLE PERSON(
	ID int NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(50) NOT null,
	AGE int(3) NOT null,
	JOB_CODE int (100)NOT NULL
);

/**
 * 職業類別
 */
CREATE TABLE JOB(
	ID int NOT NULL AUTO_INCREMENT,
	JOB_CODE int (100)NOT NULL,
	DESCRIPTION VARCHAR(50) NOT null
);